@WebApi_HostAddress = http://localhost:5072

GET {{WebApi_HostAddress}}/api/movies
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/movies/66fdf9dee4925a3805812475
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/movies
Content-Type: application/json
Accept: application/json

{
    "titulo": "Barbie",
    "diretor": "Greta Gerwig",
    "genero": ["Comédia", "Fantasia"],
    "anoLancamento": 2023,
    "sinopse": "Barbie e Ken embarcam em uma aventura no mundo real após deixar Barbieland, enfrentando os desafios da vida fora de seu universo idealizado."
}

###

PUT {{WebApi_HostAddress}}/api/movies/66ff4f9f637e3300e3fb625b
Content-Type: application/json
Accept: application/json

{
    "titulo": "Barbie: Uma Aventura no Mundo Real",
    "diretor": "Greta Gerwig",
    "genero": ["Comédia", "Fantasia"],
    "anoLancamento": 2023,
    "sinopse": "Barbie e Ken exploram o mundo real e aprendem valiosas lições sobre identidade e aceitação."
}

###

DELETE  {{WebApi_HostAddress}}/api/movies/66ff4f9f637e3300e3fb625b
Content-Type: application/json

###

GET {{WebApi_HostAddress}}/api/movies/year/2012
Content-Type: application/json