@WebApi_HostAddress = http://localhost:5072

GET {{WebApi_HostAddress}}/api/movies
Accept: application/json

###

GET {{WebApi_HostAddress}}/api/movies/66fdb2dee4925a38055ba866
Accept: application/json

###

POST {{WebApi_HostAddress}}/api/movies
Content-Type: application/json
Accept: application/json

{
    "titulo": "Barbie",
    "diretor": "Greta Gerwig",
    "genero": ["Comédia", "Fantasia"],
    "anoLancamento": 2023,
    "sinopse": "Barbie e Ken embarcam em uma aventura no mundo real após deixar Barbieland, enfrentando os desafios da vida fora de seu universo idealizado."
}

###

PUT {{WebApi_HostAddress}}/api/movies/66fdce1f3b46ef3fd43caf1d
Content-Type: application/json
Accept: application/json

{
    "titulo": "Barbie: Uma Aventura no Mundo Real",
    "diretor": "Greta Gerwig",
    "genero": ["Comédia", "Fantasia"],
    "anoLancamento": 2023,
    "sinopse": "Barbie e Ken exploram o mundo real e aprendem valiosas lições sobre identidade e aceitação."
}

###

DELETE  {{WebApi_HostAddress}}/api/movies/66fdce0d3b46ef3fd43caf1b
Content-Type: application/json

###

GET {{WebApi_HostAddress}}/api/movies/year/2023
Content-Type: application/json